export const dummyChatList = [
    {
        chatroomId: 1,
        profileImgUrl: "/images/profile1.jpg",
        nickname: "레오엄마",
        latestMessage: "안녕하세요",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "연수동",
        type: "구매",
    },
    {
        chatroomId: 2,
        profileImgUrl: "https://placehold.co/400",
        nickname: "쿠키",
        latestMessage: "안녕하세요 구매원해요~~!!",
        latestMessageDateTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 1,
        address: "봉천동",
        type: "구매",
    },
    {
        chatroomId: 3,
        profileImgUrl: "https://placehold.co/400",
        nickname: "이코코",
        latestMessage: "넹 감사합니다.",
        latestMessageDateTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "개롱동",
        type: "판매",
    },
    {
        chatroomId: 4,
        profileImgUrl: "https://placehold.co/400",
        nickname: "호두언니",
        latestMessage: "흠.. 고민해볼게요.",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 3,
        address: "청룡동",
        type: "판매",
    },
    {
        chatroomId: 5,
        profileImgUrl: "https://placehold.co/400",
        nickname: "시리",
        latestMessage: "네고 원해요",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "신림동",
        type: "판매",
    },
    {
        chatroomId: 6,
        profileImgUrl: "https://placehold.co/400",
        nickname: "반띠잉",
        latestMessage: "네네네",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 1,
        address: "강남구",
        type: "판매",
    },
    {
        chatroomId: 7,
        profileImgUrl: "https://placehold.co/400",
        nickname: "비비",
        latestMessage: "7시요",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "청담동",
        type: "판매",
    },
    {
        chatroomId: 8,
        profileImgUrl: "https://placehold.co/400",
        nickname: "지수",
        latestMessage: "hello",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "대치동",
        type: "판매",
    },
    {
        chatroomId: 9,
        profileImgUrl: "https://placehold.co/400",
        nickname: "에일리",
        latestMessage: "12시요",
        latestMessageDateTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        unreadMessageCount: 0,
        address: "신사동",
        type: "판매",
    },
];
