export const dummyItemList = [
    {
        itemId: 1,
        title: "Lorem ipsum dolor",
        imgUrl: "",
        address: "연수동",
        price: 10000,
        location: "연수역 1번 출구 앞",
        updatedAt: new Date(new Date().setMinutes(new Date().getMinutes() - 25)),
        type: "판매",
    },
    {
        itemId: 2,
        title: "consectetur adip",
        imgUrl: "https://placehold.co/400",
        address: "신사동",
        price: 0,
        location: "도산 공원 근처",
        updatedAt: new Date("2024-10-13 10:48:55"),
        type: "나눔",
    },
    {
        itemId: 3,
        title: "Lorem ipsum dolor sit am et conse ctetur adipi",
        imgUrl: "https://placehold.co/400",
        address: "연수2동",
        price: 100000000,
        location: "연수2동 행정복지센터 뒤",
        updatedAt: new Date("2024-11-12 10:48:55"),
        type: "판매",
    },
    {
        itemId: 4,
        title: "anim id est laborum",
        imgUrl: "https://placehold.co/400",
        address: "연수1동",
        price: 3400,
        location: "연수 아파트 000동",
        updatedAt: new Date(new Date().setMinutes(new Date().getMinutes() - 5)),
        type: "판매",
    },
    {
        itemId: 5,
        title: "dolor sit am et",
        imgUrl: "https://placehold.co/400",
        address: "대치동",
        price: 15000,
        location: "대치 수학 학원 건물",
        updatedAt: new Date(new Date().setMinutes(new Date().getHours() - 7)),
        type: "판매",
    },
    {
        itemId: 6,
        title: " ctetur adipianim id est laborum",
        imgUrl: "https://placehold.co/400",
        address: "역삼동",
        price: 70000,
        location: "역삼동 ㅇㅇ상가",
        updatedAt: new Date(new Date().setMinutes(new Date().getSeconds() - 5)),
        type: "판매",
    },
    {
        itemId: 7,
        title: "id est laborum aewrbpq plqab",
        imgUrl: "https://placehold.co/400",
        address: "ㅇㅇ동",
        price: 0,
        location: "ㅇㅇ빌라 ㅇㅇ동",
        updatedAt: new Date(new Date().setMinutes(new Date().getHours() - 1)),
        type: "나눔",
    },
];
